name: Notification on push

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Paris
        DISCORD_AVATAR: https://i.ibb.co/QpB0VQX/1220199700013-f.jpg
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new commit has been pushed to Ilshidur/action-discord.'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master